// Generated by `uv run needle types` from domain/audit.py — do not edit.
import type { Actor, Place } from "./card";
import type { Evidence } from "./evidence";

export const AUDIT_KIND_VALUES = ["born", "moved", "linked", "renamed", "archived", "retired", "started", "row", "answered", "discussed", "stopped", "rescued", "ended", "signal", "folded", "folded-into", "synced", "dial"] as const;
export type AuditKind = (typeof AUDIT_KIND_VALUES)[number];

export interface AuditEntry {
  id: number;
  at: string;
  actor: Actor;
  kind: AuditKind;
  card_number: number;
  from_place: Place | null;
  to_place: Place | null;
  detail: string;
  evidence?: Evidence | null;
}
