// Generated by `uv run needle types` from domain/board.py — do not edit.
import type { AuditEntry } from "./audit";
import type { Card, Place } from "./card";
import type { ColumnDefinition } from "./column";
import type { CorpusSummary } from "./corpus";
import type { Document, DocumentRef, DocumentState } from "./document";
import type { Gate } from "./gate";
import type { Project } from "./project";
import type { Row } from "./row";

export const ESSENCE_SOURCE_VALUES = ["card", "document"] as const;
export type EssenceSource = (typeof ESSENCE_SOURCE_VALUES)[number];

export interface Attention {
  asking_you: number;
  in_flight: number;
  arrived_today: number;
  documents_gone: number;
  documents_without_card: number;
}

export interface BoardState {
  project: Project;
  version: number;
  generated_at: string;
  corpus: CorpusSummary;
  attention: Attention;
  columns: ColumnView[];
  documents_without_card: DocumentRef[];
}

export interface CardDetail {
  card: Card;
  summary: CardSummary;
  brief: Row[];
  record: Row[];
  document: Document | null;
  other_citations: string[];
  history: AuditEntry[];
}

export interface CardSummary {
  number: number;
  title: string;
  essence: string | null;
  essence_source: EssenceSource | null;
  gate: Gate | null;
  tags: string[];
  document_state: DocumentState;
  document_path: string | null;
  points: number;
  is_new: boolean;
  age_date: string;
  place: Place;
}

export interface ColumnView {
  definition: ColumnDefinition;
  groups: GroupView[];
  count: number;
}

export interface GroupView {
  name: string | null;
  cards: CardSummary[];
}

export interface ProjectFile {
  path: string;
  text: string;
  read_at: string;
}
