// Generated by `uv run needle types` from domain/board.py — do not edit.
import type { AuditEntry } from "./audit";
import type { Card, Place } from "./card";
import type { ColumnDefinition } from "./column";
import type { CorpusSummary } from "./corpus";
import type { Document, DocumentRef, DocumentState, SuggestionKind } from "./document";
import type { Standing } from "./evidence";
import type { Gate } from "./gate";
import type { Collision, Conversation, Door, Doors, Lane, LaneState, Readiness } from "./lane";
import type { Project } from "./project";
import type { Row } from "./row";
import type { Reading, ReadingSession, Signal, SignalKind } from "./signal";
import type { Verdict, VerdictLine } from "./verdict";
import type { WatercoolerLine } from "./watercooler";

export const ESSENCE_SOURCE_VALUES = ["card", "document"] as const;
export type EssenceSource = (typeof ESSENCE_SOURCE_VALUES)[number];

export interface Attention {
  asking_you: number;
  in_flight: number;
  colliding: number;
  in_discussion: number;
  lanes_ended: number;
  signals_due: number;
  signals_asking: number;
  signals_reading: number;
  doubted: number;
  verdicts_unread: number;
  unplanned_defects: number;
  unplanned_ideas: number;
  arrived_today: number;
  documents_gone: number;
  documents_without_card: number;
}

export interface BoardState {
  project: Project;
  version: number;
  generated_at: string;
  corpus: CorpusSummary;
  attention: Attention;
  trunk: TrunkState;
  machine: MachineState;
  columns: ColumnView[];
  documents_without_card: DocumentRef[];
  asks: OwnerAsk[];
  verdicts: VerdictLine[];
  conversations: Conversation[];
  watercooler: WatercoolerLine[];
}

export interface CardDetail {
  card: Card;
  summary: CardSummary;
  brief: Row[];
  record: Row[];
  document: Document | null;
  other_citations: string[];
  history: AuditEntry[];
  lane: Lane | null;
  doors: Doors;
  signal: Signal | null;
  signal_note: string | null;
  readings: Reading[];
  verdict: Verdict | null;
  verdict_note: string | null;
  watercooler: WatercoolerLine[];
}

export interface CardSummary {
  number: number;
  title: string;
  essence: string | null;
  essence_source: EssenceSource | null;
  gate: Gate | null;
  tags: string[];
  document_state: DocumentState;
  document_path: string | null;
  kind: SuggestionKind | null;
  readiness: Readiness | null;
  start: Door | null;
  plan: Door | null;
  folded: FoldedCard[];
  points: number;
  is_new: boolean;
  age_date: string;
  place: Place;
  lane_state: LaneState;
  lane_sentence: string | null;
  colliding: Collision | null;
  standing: Standing;
  reading: ReadingSession | null;
}

export interface ColumnView {
  definition: ColumnDefinition;
  groups: GroupView[];
  count: number;
}

export interface FoldedCard {
  number: number;
  title: string;
  document_path: string | null;
}

export interface GroupView {
  name: string | null;
  cards: CardSummary[];
  rail: boolean;
}

export interface MachineState {
  missing: string[];
}

export interface OwnerAsk {
  number: number;
  title: string;
  what: string;
  due: string;
  kind: SignalKind;
  evidence: string | null;
}

export interface ProjectFile {
  path: string;
  text: string;
  read_at: string;
}

export interface TrunkState {
  level: boolean | null;
  behind: number;
  note: string | null;
  read_at: string | null;
}
