// Generated by `uv run needle types` from domain/board.py — do not edit.
import type { AuditEntry } from "./audit";
import type { Card, Place } from "./card";
import type { ColumnDefinition } from "./column";
import type { CorpusSummary } from "./corpus";
import type { DialState } from "./dial";
import type { Document, DocumentRef, DocumentState, Fix, SuggestionKind } from "./document";
import type { Standing } from "./evidence";
import type { Gate } from "./gate";
import type { Handouts } from "./handout";
import type { HeardMark } from "./hook";
import type { Collision, Conversation, Doors, Lane, LaneState, Progress } from "./lane";
import type { Project } from "./project";
import type { Row } from "./row";
import type { Reading, Signal, SignalKind, WindowlessSession } from "./signal";
import type { Routed, Source, Triage } from "./triage";
import type { Verdict, VerdictLine } from "./verdict";
import type { WatercoolerLine } from "./watercooler";

export const CLAIM_VALUES = ["verdict", "lane asking", "signal asking", "decision", "lane ended", "doubted", "signal overdue", "document gone", "colliding", "document without card", "no review", "lane working", "conversation", "signal reading", "planning"] as const;
export type Claim = (typeof CLAIM_VALUES)[number];

export const ESSENCE_SOURCE_VALUES = ["card", "document"] as const;
export type EssenceSource = (typeof ESSENCE_SOURCE_VALUES)[number];

export const FACE_DOOR_NAME_VALUES = ["start", "plan", "watch", "open"] as const;
export type FaceDoorName = (typeof FACE_DOOR_NAME_VALUES)[number];

export const LOOP_STATE_VALUES = ["open", "closed"] as const;
export type LoopState = (typeof LOOP_STATE_VALUES)[number];

export const MEANING_VALUES = ["yours", "broken", "live", "proven", "quiet"] as const;
export type Meaning = (typeof MEANING_VALUES)[number];

export interface Attention {
  yours: ClaimCount[];
  broken: ClaimCount[];
  live: ClaimCount[];
  unplanned_defects: number;
  unplanned_ideas: number;
  arrived_today: number;
}

export interface BoardState {
  project: Project;
  version: number;
  generated_at: string;
  corpus: CorpusSummary;
  attention: Attention;
  trunk: TrunkState;
  machine: MachineState;
  dial: DialState;
  columns: ColumnView[];
  documents_without_card: DocumentRef[];
  asks: OwnerAsk[];
  verdicts: VerdictLine[];
  conversations: Conversation[];
  watercooler: WatercoolerLine[];
}

export interface CardDetail {
  card: Card;
  summary: CardSummary;
  brief: Row[];
  record: Row[];
  document: Document | null;
  other_citations: string[];
  history: AuditEntry[];
  lane: Lane | null;
  doors: Doors;
  signal: Signal | null;
  signal_note: string | null;
  trigger: Signal | null;
  trigger_note: string | null;
  readings: Reading[];
  verdict: Verdict | null;
  verdict_note: string | null;
  watercooler: WatercoolerLine[];
  heard: HeardMark | null;
  handouts: Handouts;
  triage: Triage | null;
  triaging: WindowlessSession | null;
  source: Source | null;
}

export interface CardState {
  word: string;
  meaning: Meaning;
  detail: string | null;
  loop: Loop | null;
  door: FaceDoor | null;
  hint: string | null;
}

export interface CardSummary {
  number: number;
  title: string;
  essence: string | null;
  essence_source: EssenceSource | null;
  gate: Gate | null;
  tags: string[];
  document_state: DocumentState;
  document_path: string | null;
  kind: SuggestionKind | null;
  fix: Fix | null;
  routing: Routed | null;
  state: CardState;
  claims: Claim[];
  folded: FoldedCard[];
  is_new: boolean;
  age_date: string;
  place: Place;
  lane_state: LaneState;
  colliding: Collision | null;
  progress: Progress | null;
  standing: Standing;
  reading: WindowlessSession | null;
  planning: WindowlessSession | null;
  triaging: WindowlessSession | null;
  triage: Triage | null;
}

export interface ClaimCount {
  claim: Claim;
  count: number;
  label: string;
}

export interface ColumnView {
  definition: ColumnDefinition;
  groups: GroupView[];
  count: number;
}

export interface FaceDoor {
  name: FaceDoorName;
  label: string;
  why: string;
  primary: boolean;
}

export interface FoldedCard {
  number: number;
  title: string;
  document_path: string | null;
}

export interface GroupView {
  name: string | null;
  cards: CardSummary[];
  rail: boolean;
}

export interface Loop {
  state: LoopState;
  owner_only: boolean;
}

export interface MachineState {
  missing: string[];
  roles?: string[] | null;
}

export interface OwnerAsk {
  number: number;
  title: string;
  what: string;
  due: string;
  kind: SignalKind;
  evidence: string | null;
}

export interface ProjectFile {
  path: string;
  text: string;
  read_at: string;
}

export interface TrunkState {
  level: boolean | null;
  behind: number;
  note: string | null;
  read_at: string | null;
}

export const CLAIM_MEANING: Record<Claim, Meaning> = {
  "verdict": "yours",
  "lane asking": "yours",
  "signal asking": "yours",
  "decision": "yours",
  "lane ended": "broken",
  "doubted": "broken",
  "signal overdue": "broken",
  "document gone": "broken",
  "colliding": "broken",
  "document without card": "broken",
  "no review": "broken",
  "lane working": "live",
  "conversation": "live",
  "signal reading": "live",
  "planning": "live",
};
