// Generated by `uv run needle types` from domain/call.py — do not edit.

export const CALL_OUTCOME_VALUES = ["landed", "nothing", "blocked", "moved", "ended"] as const;
export type CallOutcome = (typeof CALL_OUTCOME_VALUES)[number];

export interface Call {
  id: number;
  session_id: string;
  slot: string;
  name: string;
  note: string;
  answer: string;
  brief: string;
  caller: string;
  called_at: string;
  moved: string | null;
  ended_at: string | null;
  words: string | null;
}

export interface CallVerdict {
  outcome: CallOutcome;
  words: string;
  session_id: string;
  slot: string;
}
