// Generated by `uv run needle types` from domain/card.py — do not edit.
import type { Column } from "./column";
import type { DocumentKind } from "./document";
import type { Gate } from "./gate";
import type { Row } from "./row";

export const ACTOR_VALUES = ["owner", "session", "import", "corpus", "machine"] as const;
export type Actor = (typeof ACTOR_VALUES)[number];

export const CARD_ORIGIN_VALUES = ["imported", "founding", "arrived"] as const;
export type CardOrigin = (typeof CARD_ORIGIN_VALUES)[number];

export interface Card {
  number: number;
  project: string;
  place: Place;
  title: string;
  gate: Gate | null;
  tags: string[];
  deep: string;
  citations: string[];
  link: DocumentLink | null;
  origin: CardOrigin;
  born_at: string;
  rows: Row[];
}

export interface DocumentLink {
  kind: DocumentKind;
  stem: string;
  title: string;
  archived: boolean;
}

export interface Move {
  to: Place;
}

export interface Place {
  column: Column;
  group: string | null;
  position: number;
}
