// Generated by `uv run needle types` from domain/column.py — do not edit.

export const COLUMN_VALUES = ["Backlog", "Planned", "Up next", "Executing", "Decision moment", "Executed", "Done", "Not now"] as const;
export type Column = (typeof COLUMN_VALUES)[number];

export interface ColumnDefinition {
  column: Column;
  note: string;
  definition: string[];
  moved_by: string;
  ranked: boolean;
  yours: boolean;
  furled_on_laptop: boolean;
}
