// Generated by `uv run needle types` from domain/corpus.py — do not edit.
import type { Document } from "./document";
import type { FocusDocument } from "./focus";

export interface CorpusIndex {
  documents: Document[];
  focus?: FocusDocument | null;
  read_at: string;
}

export interface CorpusSummary {
  live_plans: number;
  live_suggestions: number;
  archived: number;
  watching: boolean;
  watch_note: string | null;
  read_at: string;
}
