// Generated by `uv run needle types` from domain/dial.py — do not edit.
import type { Actor } from "./card";

export const FILER_VALUES = ["fix lane", "feature lane", "reading session", "owner", "unknown"] as const;
export type Filer = (typeof FILER_VALUES)[number];

export const FIX_STAGE_VALUES = ["planning", "planned", "started", "folded", "asked", "ended"] as const;
export type FixStage = (typeof FIX_STAGE_VALUES)[number];

export interface Dial {
  on: boolean;
  lanes: number;
  changed_at: string | null;
  first_on_at: string | null;
}

export interface DialChange {
  id: number;
  at: string;
  actor: Actor;
  on: boolean;
  lanes: number;
}

export interface DialState {
  dial: Dial;
  running: number;
  quiet: boolean;
}

export interface FixLane {
  id: number;
  project: string;
  card_number: number;
  stage: FixStage;
  planning_started_at: string;
  planned_at: string | null;
  started_at: string | null;
  ended_at: string | null;
  note: string | null;
}

export interface FixReport {
  project: string;
  card_number: number;
  title: string;
  stage: FixStage;
  folded: boolean;
  reviewed: boolean;
  stopped_to_ask: boolean;
  defect_filed_against: boolean;
  fold_reverted: boolean;
  class_closer: string | null;
}

export interface Fixes {
  dial: Dial;
  lanes: FixReport[];
  rail_now: RailCount[];
  rail_at_first_on: RailCount[];
}

export interface RailCount {
  project: string;
  counts: Record<string, number>;
  total: number;
}
