// Generated by `uv run needle types` from domain/document.py — do not edit.
import type { Gate } from "./gate";
import type { Handout } from "./handout";

export const DOCUMENT_KIND_VALUES = ["plan", "suggestion"] as const;
export type DocumentKind = (typeof DOCUMENT_KIND_VALUES)[number];

export const DOCUMENT_STATE_VALUES = ["plan", "suggestion", "archived", "note", "gone"] as const;
export type DocumentState = (typeof DOCUMENT_STATE_VALUES)[number];

export const FIX_MARK_VALUES = ["now", "when", "his"] as const;
export type FixMark = (typeof FIX_MARK_VALUES)[number];

export const STANCE_VALUES = ["met", "deviated"] as const;
export type Stance = (typeof STANCE_VALUES)[number];

export const SUGGESTION_KIND_VALUES = ["idea", "defect"] as const;
export type SuggestionKind = (typeof SUGGESTION_KIND_VALUES)[number];

export interface Document {
  kind: DocumentKind;
  stem: string;
  path: string;
  archived: boolean;
  title: string;
  date: string | null;
  status: string | null;
  status_word: string | null;
  gate: Gate | null;
  gate_why: string | null;
  sequencing: string | null;
  sequenced?: SequencedCard[];
  found_by: string | null;
  card_ref: number | null;
  suggestion_kind: SuggestionKind | null;
  fix?: Fix | null;
  fix_note?: string | null;
  cites: string[];
  handouts: Handout[];
  items: Item[];
  head_fields: HeadField[];
  intent_heading: string | null;
  intent: string;
  essence: string | null;
  read_at: string;
}

export interface DocumentRef {
  kind: DocumentKind;
  stem: string;
  path: string;
  title: string;
}

export interface Fix {
  mark: FixMark;
  why: string | null;
  trigger: string | null;
}

export interface HeadField {
  key: string;
  value: string;
}

export interface Item {
  number: number;
  title: string;
  done_means: string | null;
  stance: Stance | null;
  text: string | null;
}

export interface Review {
  path: string;
  plan_stem: string | null;
  passes: ReviewPass[];
  clean: boolean;
  found: number;
  fixed: number;
  no_change: number;
  filed: number;
  filed_names: string[];
}

export interface ReviewPass {
  number: number;
  lens: string;
  text: string;
  clean: boolean;
}

export interface SequencedCard {
  words: string | null;
  number: number;
}
