// Generated by `uv run needle types` from domain/ending.py — do not edit.

export const CAUSE_VALUES = ["its allowance ran out", "the machine took back its memory", "the machine took back its account's memory", "the laptop went down", "the connection came back", "the stronger model is back", "it was stopped through its account", "the cause is not established"] as const;
export type Cause = (typeof CAUSE_VALUES)[number];

export const DISPOSITION_VALUES = ["closed", "the owner's", "unfinished"] as const;
export type Disposition = (typeof DISPOSITION_VALUES)[number];

export interface Boot {
  index: number;
  boot_id: string;
  first_entry: string;
  last_entry: string;
}

export interface Death {
  session_id: string;
  project: string;
  card_number: number;
  cause: Cause;
  words: string;
  evidence: string;
  last_alive_at: string | null;
  named_at: string;
  settled: boolean;
}

export interface Named {
  cause: Cause;
  words: string;
  evidence: string;
  last_alive_at: string | null;
  settled: boolean;
}

export interface Park {
  id: number;
  project: string;
  card_number: number;
  session_id: string;
  cause: Cause;
  words: string;
  waits_on: string;
  until: string | null;
  held_since: string | null;
  started_at: string;
  lifted_at: string | null;
  lifted_words: string | null;
}

export interface Recovery {
  id: number;
  project: string;
  card_number: number;
  session_id: string;
  cause: Cause;
  words: string;
  started_at: string;
  replacement: string | null;
  verdict: string | null;
  ended_at: string | null;
  note: string | null;
}

export interface Sighting {
  session_id: string;
  project: string;
  card_number: number;
  pid: number;
  scope: string | null;
  boot_id: string | null;
  first_seen: string;
  last_seen: string;
  released_at?: string | null;
  scoped_at?: string | null;
}

export const MACHINE_ENDED: readonly Cause[] = ["its allowance ran out", "the connection came back", "the laptop went down", "the machine took back its account's memory", "the machine took back its memory", "the stronger model is back"];
