// Generated by `uv run needle types` from domain/entrance.py — do not edit.

export const ENTRANCE_WORD_VALUES = ["one-text", "two-texts", "none"] as const;
export type EntranceWord = (typeof ENTRANCE_WORD_VALUES)[number];

export interface Entrance {
  word: EntranceWord;
  line: string;
  files: InjectedFile[];
  read_at: string;
}

export interface InjectedFile {
  path: string;
  resolves_to: string | null;
  is_the_one_text: boolean;
}
