// Generated by `uv run needle types` from domain/evidence.py — do not edit.
import type { Actor } from "./card";

export const EVIDENCE_VALUES = ["hands-on", "close-landed", "signal-delivered", "signal-failed", "lane-ended", "document-archived", "plan-live"] as const;
export type Evidence = (typeof EVIDENCE_VALUES)[number];

export const EVIDENCE_STATE_VALUES = ["held", "doubted", "unknown", "trusted"] as const;
export type EvidenceState = (typeof EVIDENCE_STATE_VALUES)[number];

export interface Standing {
  actor: Actor;
  evidence: Evidence | null;
  state: EvidenceState;
  words: string | null;
}
