// Generated by `uv run needle types` from domain/focus.py — do not edit.
import type { HowKnown } from "./call";
import type { Place } from "./card";
import type { Column } from "./column";
import type { Conversation, Door } from "./lane";
import type { Signal, SignalKind } from "./signal";

export const FOCUS_STATE_VALUES = ["no focus", "outcome only", "talking", "ended without", "proposed", "chosen", "paused"] as const;
export type FocusState = (typeof FOCUS_STATE_VALUES)[number];

export const FOCUS_VERDICT_VALUES = ["stands", "does not stand", "cannot tell"] as const;
export type FocusVerdict = (typeof FOCUS_VERDICT_VALUES)[number];

export const LEVERAGE_VALUES = ["helps remove this limit", "protects progress", "does not address this limit", "needs evidence"] as const;
export type Leverage = (typeof LEVERAGE_VALUES)[number];

export const LEVERAGE_STATE_VALUES = ["read", "unread", "stale", "reading"] as const;
export type LeverageState = (typeof LEVERAGE_STATE_VALUES)[number];

export const LIKELIHOOD_VALUES = ["high", "medium", "low"] as const;
export type Likelihood = (typeof LIKELIHOOD_VALUES)[number];

export const MEASURE_SIDE_VALUES = ["outcome", "bottleneck"] as const;
export type MeasureSide = (typeof MEASURE_SIDE_VALUES)[number];

export const READING_KIND_VALUES = ["check", "card", "recheck"] as const;
export type ReadingKind = (typeof READING_KIND_VALUES)[number];

export const RECHECK_OUTCOME_VALUES = ["holds", "diagnosis challenged", "work not linked", "expired"] as const;
export type RecheckOutcome = (typeof RECHECK_OUTCOME_VALUES)[number];

export interface Acceptance {
  id: number;
  project: string;
  at: string;
  focus_fingerprint: string;
  moves: AcceptedMove[];
  put_back_at: string | null;
  note: string | null;
}

export interface AcceptedMove {
  number: number;
  from_place: Place;
  to_place: Place;
  why: string;
}

export interface ArrangedColumn {
  column: Column;
  groups: ArrangedGroup[];
}

export interface ArrangedGroup {
  name: string | null;
  rail: boolean;
  numbers: number[];
}

export interface Arrangement {
  available: boolean;
  why: string | null;
  columns: ArrangedColumn[];
  moves: ProposedMove[];
}

export interface CardLeverage {
  state: LeverageState;
  leverage: Leverage | null;
  likelihood: Likelihood | null;
  words: string | null;
  sentence: string;
  hold: string | null;
  read_at: string | null;
}

export interface CheckAnswer {
  verdict: FocusVerdict;
  line: string;
  how_known: HowKnown;
  sources: string[];
}

export interface Coverage {
  assessed: number;
  total: number;
  unread: number;
  needs_evidence: number;
  stale: number;
  reading: number;
  queued_helping: number;
  line: string;
}

export interface Decline {
  id: number;
  project: string;
  card_number: number;
  focus_fingerprint: string;
  document_fingerprint: string;
  leverage: Leverage;
  at: string;
}

export interface FocusCall {
  id: number;
  project: string;
  kind: ReadingKind;
  card_number: number | null;
  fingerprint: string;
  document_fingerprint: string | null;
  call_id: number | null;
  session_id: string | null;
  opened_at: string;
  ended_at: string | null;
  landed: boolean;
  note: string | null;
}

export interface FocusCheck {
  id: number;
  project: string;
  fingerprint: string;
  at: string;
  verdict: FocusVerdict;
  line: string;
  how_known: HowKnown | null;
  session_id: string | null;
}

export interface FocusDocument {
  path: string;
  fingerprint: string;
  title: string;
  what_matters: string | null;
  outcome: Measure;
  what_holds: string | null;
  bottleneck: Measure;
  evidence: string | null;
  rival: string | null;
  recheck: Measure;
  proposed: string | null;
  doubts: string[];
  read_at: string;
}

export interface FocusRecheck {
  id: number;
  project: string;
  fingerprint: string;
  at: string;
  outcome: RecheckOutcome;
  words: string;
  session_id: string | null;
}

export interface FocusRuling {
  id: number;
  project: string;
  fingerprint: string;
  what_matters: string;
  chosen_at: string;
}

export interface FocusStrip {
  state: FocusState;
  sentence: string;
  what_matters: string | null;
  what_holds: string | null;
  document: FocusDocument | null;
  ruling: FocusRuling | null;
  check: FocusCheck | null;
  checking: boolean;
  check_note: string | null;
  conversation: Conversation | null;
  coverage: Coverage | null;
  moves_proposed: number;
  accepted: Acceptance | null;
  put_back_offered: boolean;
  paused: string | null;
  recheck_due: string | null;
  recheck: FocusRecheck | null;
  measures: MeasureReading[];
  talk: Door;
  choose: Door;
  propose: Door;
}

export interface LeverageAnswer {
  leverage: Leverage;
  likelihood: Likelihood | null;
  why: string;
  how_known: HowKnown;
  sources: string[];
}

export interface LeverageReading {
  id: number;
  project: string;
  card_number: number;
  at: string;
  leverage: Leverage;
  likelihood: Likelihood | null;
  words: string;
  focus_fingerprint: string;
  document_fingerprint: string;
  session_id: string | null;
}

export interface Measure {
  line: string | null;
  signal: Signal | null;
  note: string | null;
}

export interface MeasureReading {
  id: number;
  project: string;
  fingerprint: string;
  side: MeasureSide;
  at: string;
  delivered: boolean | null;
  words: string;
  baseline: boolean;
}

export interface ProposedMove {
  number: number;
  from_place: Place;
  to_place: Place;
  why: string;
  wake: string | null;
}

export interface RecheckAnswer {
  outcome: RecheckOutcome;
  words: string;
  how_known: HowKnown;
  sources: string[];
}

export const MACHINE_READ_KINDS: readonly SignalKind[] = ["command", "file", "url"];
