// Generated by `uv run needle types` from domain/handout.py — do not edit.

export interface Dispatch {
  role: string;
  session_id: string;
  at: string | null;
}

export interface Handout {
  item: string | null;
  role: string;
  what: string;
  verifies: string | null;
}

export interface Handouts {
  named: Handout[];
  unknown: string[];
  verdict: string | null;
}
