// Generated by `uv run needle types` from domain/hook.py — do not edit.

export const HOOK_KIND_VALUES = ["SessionStart", "Stop", "SessionEnd", "StopFailure"] as const;
export type HookKind = (typeof HOOK_KIND_VALUES)[number];

export interface HookEvent {
  kind: HookKind;
  session_id: string;
  cwd: string;
  at: string;
  source: string | null;
  message: string | null;
  reason: string | null;
  error: string | null;
  transcript_path: string | null;
  id: number;
  project: string | null;
  card_number: number | null;
}

export interface HookPosted {
  kind: HookKind;
  session_id: string;
  cwd: string;
  at: string;
  source: string | null;
  message: string | null;
  reason: string | null;
  error: string | null;
  transcript_path: string | null;
}
