// Generated by `uv run needle types` from domain/lane.py — do not edit.
import type { Column } from "./column";
import type { Item, Review } from "./document";
import type { Session } from "./session";
import type { Placement } from "./slot";
import type { WindowKind } from "./window";

export const COLLISION_VERDICT_VALUES = ["clear", "collides", "unknown"] as const;
export type CollisionVerdict = (typeof COLLISION_VERDICT_VALUES)[number];

export const LANE_STATE_VALUES = ["none", "working", "asking", "stopped", "blocked", "moving", "ended"] as const;
export type LaneState = (typeof LANE_STATE_VALUES)[number];

export const START_STATE_VALUES = ["free", "shares", "waits", "no gate", "nowhere to run", "lane exists", "elsewhere", "unread"] as const;
export type StartState = (typeof START_STATE_VALUES)[number];

export interface Collision {
  verdict: CollisionVerdict;
  sentence: string;
  files: string[];
  cards: number[];
}

export interface Conversation {
  short_id: string;
  slot: string;
  card_number: number | null;
  what: string;
  started_at: string;
}

export interface Discussion {
  id: number;
  project: string;
  card_number: number | null;
  kind: WindowKind;
  session_id: string;
  slot: string;
  started_at: string;
}

export interface Door {
  offered: boolean;
  label: string;
  why: string;
}

export interface DoorResult {
  door: string;
  said: string;
}

export interface Doors {
  start: Door;
  readiness: Readiness;
  placement: Placement | null;
  placement_note: string;
  collision: Collision | null;
  waits: Wait[];
  watch: Door;
  answer: Door;
  discuss: Door;
  plan: Door;
  look: Door;
  resume: Door;
  stop: Door;
  signal: Door;
}

export interface Lane {
  card_number: number;
  name: string;
  path: string | null;
  state: LaneState;
  sentence: string;
  session: Session | null;
  question: string | null;
  said: string | null;
  said_at: string | null;
  discussing: string[];
  window_open: boolean;
  hands_on_since: string | null;
  died: string | null;
  moved: string | null;
  folded: boolean;
  trunk_synced: boolean;
  main_synced: boolean;
  edits: string[];
  declared: string[];
  colliding: Collision | null;
  progress?: Progress | null;
}

export interface LaneRecord {
  project: string;
  card_number: number;
  name: string;
  path: string;
  branch: string | null;
  birth: string | null;
  tip: string | null;
  first_seen: string;
  last_seen: string;
  gone_at: string | null;
  folded_at: string | null;
  trunk_synced_at: string | null;
  main_synced_at: string | null;
}

export interface LaneSnapshot {
  lanes: Record<string, Lane>;
  doors: Record<string, Doors>;
  conversations: Conversation[];
  read_at: string;
}

export interface Progress {
  items: Item[];
  met: number;
  deviated: number;
  total: number;
  last: string | null;
  read_at: string;
  review: Review | null;
  line: string;
}

export interface Readiness {
  state: StartState;
  why: string;
  cards: number[];
  files: string[];
  waits: Wait[];
}

export interface Wait {
  label: string;
  project: string;
  number: number;
  column: Column | null;
  shipped: boolean;
}

export const HANDS_ON: readonly LaneState[] = ["asking", "blocked", "moving", "stopped", "working"];
