// Generated by `uv run needle types` from domain/lane.py — do not edit.
import type { Session } from "./session";
import type { Placement } from "./slot";

export const COLLISION_VERDICT_VALUES = ["clear", "collides", "unknown"] as const;
export type CollisionVerdict = (typeof COLLISION_VERDICT_VALUES)[number];

export const LANE_STATE_VALUES = ["none", "working", "asking", "stopped", "blocked", "moving", "ended"] as const;
export type LaneState = (typeof LANE_STATE_VALUES)[number];

export interface Collision {
  verdict: CollisionVerdict;
  sentence: string;
  files: string[];
}

export interface Conversation {
  short_id: string;
  slot: string;
  card_number: number | null;
  what: string;
  started_at: string;
}

export interface Discussion {
  id: number;
  project: string;
  card_number: number | null;
  session_id: string;
  slot: string;
  started_at: string;
}

export interface Door {
  offered: boolean;
  label: string;
  why: string;
}

export interface DoorResult {
  door: string;
  said: string;
}

export interface Doors {
  start: Door;
  start_anyway: Door;
  placement: Placement | null;
  placement_note: string;
  collision: Collision | null;
  watch: Door;
  answer: Door;
  discuss: Door;
  look: Door;
  resume: Door;
  stop: Door;
  signal: Door;
}

export interface Lane {
  card_number: number;
  name: string;
  path: string | null;
  state: LaneState;
  sentence: string;
  session: Session | null;
  question: string | null;
  said: string | null;
  said_at: string | null;
  discussing: string[];
  window_open: boolean;
  hands_on_since: string | null;
  died: string | null;
  moved: string | null;
  folded: boolean;
  trunk_synced: boolean;
  main_synced: boolean;
  edits: string[];
  declared: string[];
  colliding: Collision | null;
}

export interface LaneRecord {
  project: string;
  card_number: number;
  name: string;
  path: string;
  branch: string | null;
  birth: string | null;
  tip: string | null;
  first_seen: string;
  last_seen: string;
  gone_at: string | null;
  folded_at: string | null;
  trunk_synced_at: string | null;
  main_synced_at: string | null;
}

export interface LaneSnapshot {
  lanes: Record<string, Lane>;
  doors: Record<string, Doors>;
  conversations: Conversation[];
  read_at: string;
}

export const HANDS_ON: readonly LaneState[] = ["asking", "blocked", "moving", "stopped", "working"];
