// Generated by `uv run needle types` from domain/launch.py — do not edit.
import type { Gate } from "./gate";
import type { Session } from "./session";
import type { Placement, Rung } from "./slot";

export const LAUNCH_VERDICT_VALUES = ["alive", "dead", "unconfirmed"] as const;
export type LaunchVerdict = (typeof LAUNCH_VERDICT_VALUES)[number];

export interface Attempt {
  rung: Rung;
  verdict: LaunchVerdict;
  short_id: string | null;
  reason: string | null;
  seconds: number;
}

export interface Launch {
  card: string;
  verdict: LaunchVerdict;
  session: Session | null;
  placement: Placement | null;
  scope: string | null;
  attempts: Attempt[];
  reason: string | null;
}

export interface Rescue {
  id: number;
  session_id: string;
  from_rung: Rung | null;
  to_rung: Rung;
  reason: string;
  at: string;
}

export interface Start {
  repo: string;
  card: string;
  brief: string;
  effort: Gate;
  from_slot: string | null;
}

export interface Stopped {
  short_id: string;
  session_id: string;
  slot: string;
  gone: boolean;
  seconds: number;
  words: string;
}
