// Generated by `uv run needle types` from domain/machine.py — do not edit.
import type { Headroom } from "./dial";

export interface BoardMachine {
  name: string;
  host: string;
  command: string;
}

export interface HighWater {
  machine: string;
  day: string;
  least_available: number;
  total: number;
  at: string;
}

export interface Machine {
  name: string;
  machine_id: string;
  host: string | null;
  desktop: boolean;
  ground: string | null;
  command: string;
  added_at: string;
}

export interface MachineRoom {
  machine: Machine;
  here: boolean;
  room: Headroom | null;
  why: string | null;
  high_water: HighWater | null;
  killed: number;
  timings?: Timing[];
}

export interface Timing {
  machine: string;
  what: string;
  seconds: number;
  at: string;
}
