// Generated by `uv run needle types` from domain/machine.py — do not edit.
import type { Headroom, ScopeHeld } from "./dial";
import type { Boot } from "./ending";
import type { LaneDocs, LaneTip } from "./lane";
import type { Session } from "./session";
import type { Limits, Where } from "./slot";

export interface Ask {
  repos?: string[];
  lanes?: LaneAsk[];
  hold?: boolean;
  owners?: Record<string, [string, number]>;
  read?: string[];
}

export interface BoardMachine {
  name: string;
  host: string;
  command: string;
}

export interface HighWater {
  machine: string;
  day: string;
  least_available: number;
  total: number;
  at: string;
}

export interface LaneAsk {
  checkout: string;
  repo: string;
  branch: string | null;
  plans?: string[];
  reviews?: boolean;
}

export interface LaneSeen {
  checkout: string;
  tip: LaneTip;
  edits: string[];
  docs: LaneDocs;
  plans?: string[];
  reviews?: boolean;
}

export interface Machine {
  name: string;
  machine_id: string;
  host: string | null;
  desktop: boolean;
  ground: string | null;
  command: string;
  added_at: string;
}

export interface MachineRoom {
  machine: Machine;
  here: boolean;
  room: Headroom | null;
  why: string | null;
  high_water: HighWater | null;
  killed: number;
  timings?: Timing[];
  clones?: string[];
  observed_at?: string | null;
  behind?: boolean;
}

export interface Observation {
  at: string;
  seconds: number;
  sessions: Session[];
  boots: Boot[];
  room: Headroom;
  scopes: ScopeHeld[] | null;
  placement: Where;
  checkouts?: Record<string, Record<string, string | null>>;
  lanes?: LaneSeen[];
  limits?: Record<string, Limits | null>;
  windows?: string[] | null;
}

export interface Observed {
  machine: string;
  observation: Observation | null;
  read_at: string | null;
  asked_at?: string | null;
  fresh: boolean;
  why: string | null;
  behind?: boolean;
  seconds?: number;
}

export interface Timing {
  machine: string;
  what: string;
  seconds: number;
  at: string;
}
