// Generated by `uv run needle types` from domain/meaning.py — do not edit.

export const MEANING_VALUES = ["yours", "broken", "live", "proven", "quiet"] as const;
export type Meaning = (typeof MEANING_VALUES)[number];

export const OPENING: Record<Meaning, string> = {
  "yours": "Your move",
  "broken": "Something is wrong",
  "live": "Happening now",
  "proven": "Proven",
  "quiet": "Nothing for you",
};
