// Generated by `uv run needle types` from domain/neighbour.py — do not edit.
import type { DocumentKind, SuggestionKind } from "./document";

export const NEIGHBOUR_GROUND_VALUES = ["files", "words"] as const;
export type NeighbourGround = (typeof NEIGHBOUR_GROUND_VALUES)[number];

export interface Beside {
  neighbours: Neighbour[];
  unnamed: number[];
  counted: boolean;
  born: string | null;
  sentence: string | null;
  clears: string | null;
}

export interface Neighbour {
  number: number;
  title: string;
  essence: string | null;
  kind: DocumentKind;
  suggestion_kind: SuggestionKind | null;
  path: string;
  ground: NeighbourGround;
  files: string[];
  words: string[];
  named: boolean;
  rulings: string[];
}
