// Generated by `uv run needle types` from domain/notice.py — do not edit.

export const MOMENT_VALUES = ["moved on", "needs you"] as const;
export type Moment = (typeof MOMENT_VALUES)[number];

export interface Notice {
  project: string;
  project_name: string;
  card_number: number;
  title: string;
  words: string;
  moment: Moment;
}

export interface Shown {
  id: number;
  project: string;
  card_number: number;
  at: string;
}

export interface Told {
  raised: boolean;
  words: string;
}
