// Generated by `uv run needle types` from domain/project.py — do not edit.
import type { Entrance } from "./entrance";

export interface Project {
  slug: string;
  name: string;
  path: string;
  registered_at: string;
  entrance?: Entrance | null;
}
