// Generated by `uv run needle types` from domain/release.py — do not edit.

export interface Held {
  project: string;
  carries: string[];
  files: string[];
  commits: number;
  hold: string | null;
  hold_stands: boolean;
  cards: number[];
  claimed: boolean;
  sentence: string;
  read_at: string;
}

export interface Release {
  files: string[];
  commits: number;
  read: boolean;
  note: string | null;
  read_at?: string | null;
}

export interface Undoable {
  paths: string[];
  hold: string | null;
  declared_at: string;
}
