// Generated by `uv run needle types` from domain/row.py — do not edit.

export const ROW_HALF_VALUES = ["essence", "brief", "record"] as const;
export type RowHalf = (typeof ROW_HALF_VALUES)[number];

export const ROW_KIND_VALUES = ["SERVES", "TODAY", "COST", "YOUR TIME", "WAITS", "PLAN", "REC", "Q", "ASK", "WHY", "WHY NOW", "STAKES", "STATE", "ITEMS", "OPEN", "WHAT", "WEEK", "DELIVERED", "WATCH", "REVIEW", "RULING", "RULED", "DONE"] as const;
export type RowKind = (typeof ROW_KIND_VALUES)[number];

export interface Row {
  kind: RowKind;
  text: string;
}

export const ROW_HALF: Record<RowKind, RowHalf> = {
  "SERVES": "essence",
  "TODAY": "brief",
  "COST": "brief",
  "YOUR TIME": "brief",
  "WAITS": "brief",
  "PLAN": "brief",
  "REC": "brief",
  "Q": "brief",
  "ASK": "brief",
  "WHY": "brief",
  "WHY NOW": "brief",
  "STAKES": "brief",
  "STATE": "brief",
  "ITEMS": "brief",
  "OPEN": "brief",
  "WHAT": "brief",
  "WEEK": "brief",
  "DELIVERED": "record",
  "WATCH": "record",
  "REVIEW": "record",
  "RULING": "record",
  "RULED": "record",
  "DONE": "record",
};

export const LEAD_ROWS: readonly RowKind[] = ["TODAY"];

export const LANDED_ROWS: readonly RowKind[] = ["DELIVERED"];

export const ASK_ROWS: readonly RowKind[] = ["ASK", "Q", "WATCH", "YOUR TIME"];
