// Generated by `uv run needle types` from domain/session.py — do not edit.
import type { Gate } from "./gate";
import type { Handoff, Model } from "./slot";

export const SESSION_KIND_VALUES = ["background", "interactive"] as const;
export type SessionKind = (typeof SESSION_KIND_VALUES)[number];

export const SESSION_STATE_VALUES = ["working", "blocked", "idle", "done", "ended"] as const;
export type SessionState = (typeof SESSION_STATE_VALUES)[number];

export interface Doing {
  step: string;
  at: string;
}

export interface Session {
  slot: string;
  config_dir: string;
  short_id: string;
  session_id: string;
  kind: SessionKind;
  name: string;
  cwd: string;
  worktree: string | null;
  state: SessionState;
  recorded: string;
  detail: string;
  pid: number | null;
  scope: string | null;
  model: Model | null;
  effort: Gate | null;
  stale: boolean;
  wall: Handoff | null;
  intent: string;
  created_at: string | null;
  updated_at: string | null;
  resumed_from: string | null;
  doing: Doing | null;
}

export interface SessionSlot {
  session_id: string;
  slot: string;
  card: string;
  scope: string;
  recorded_at: string;
}
