// Generated by `uv run needle types` from domain/signal.py — do not edit.

export const SIGNAL_KIND_VALUES = ["url", "file", "command", "owner"] as const;
export type SignalKind = (typeof SIGNAL_KIND_VALUES)[number];

export interface Reading {
  id: number;
  card_number: number;
  at: string;
  delivered: boolean | null;
  words: string;
}

export interface Signal {
  what: string;
  kind: SignalKind;
  target: string;
  expect: string | null;
  due: string;
  every_hours: number;
}
