// Generated by `uv run needle types` from domain/signal.py — do not edit.
import type { Actor } from "./card";

export const FINDING_VALUES = ["delivered", "not-delivered", "cannot-tell"] as const;
export type Finding = (typeof FINDING_VALUES)[number];

export const SIGNAL_KIND_VALUES = ["url", "file", "command", "session", "owner"] as const;
export type SignalKind = (typeof SIGNAL_KIND_VALUES)[number];

export interface Reading {
  id: number;
  card_number: number;
  at: string;
  delivered: boolean | null;
  words: string;
  actor: Actor;
}

export interface ReadingSession {
  id: number;
  project: string;
  card_number: number;
  session_id: string;
  slot: string;
  started_at: string;
  ended_at: string | null;
}

export interface Signal {
  what: string;
  kind: SignalKind;
  target: string;
  expect: string | null;
  due: string;
  every_hours: number;
}
