// Generated by `uv run needle types` from domain/slot.py — do not edit.

export const MODEL_VALUES = ["fable", "opus"] as const;
export type Model = (typeof MODEL_VALUES)[number];

export interface Handoff {
  session_id: string;
  short_id: string | null;
  from_slot: string;
  account: string;
  model: Model | null;
  prompt: string;
  reason: string;
  at: string;
  cwd: string | null;
  worktree: string | null;
  pid: number | null;
  stopped: boolean | null;
  path: string;
}

export interface Placement {
  slot: string;
  model: Model;
  config_dir: string;
  why: string;
}

export interface Rung {
  slot: string;
  model: Model | null;
}

export interface Slot {
  name: string;
  config_dir: string;
}

export interface Where {
  placement: Placement | null;
  reason: string;
}
