// Generated by `uv run needle types` from domain/slot.py — do not edit.

export const MAKE_VALUES = ["claude", "codex"] as const;
export type Make = (typeof MAKE_VALUES)[number];

export interface Handoff {
  session_id: string;
  short_id: string | null;
  from_slot: string;
  account: string;
  model: string | null;
  prompt: string;
  reason: string;
  at: string;
  cwd: string | null;
  worktree: string | null;
  pid: number | null;
  stopped: boolean | null;
  path: string;
}

export interface Placement {
  slot: string;
  make: Make;
  model: string | null;
  config_dir: string;
  why: string;
  tier?: Tier | null;
}

export interface Rung {
  slot: string;
  model: string | null;
}

export interface Slot {
  name: string;
  config_dir: string;
}

export interface Tier {
  rank: number;
  ruled_on: string;
  why: string;
}

export interface Where {
  placement: Placement | null;
  reason: string;
}
