// Generated by `uv run needle types` from domain/team.py — do not edit.
import type { Make } from "./slot";

export const CHALLENGE_VALUES = ["alone", "same-make", "different-make"] as const;
export type Challenge = (typeof CHALLENGE_VALUES)[number];

export const CONCLUSION_VALUES = ["earned", "best-quality", "tied", "exploring", "unavailable", "stale", "pinned"] as const;
export type Conclusion = (typeof CONCLUSION_VALUES)[number];

export const SHAPE_VALUES = ["judgment", "bounded", "reading"] as const;
export type Shape = (typeof SHAPE_VALUES)[number];

export interface Composition {
  project: string;
  card_number: number;
  route: Route;
  assigned_at: string;
}

export interface Hand {
  make: Make;
  model: string | null;
  slot: string;
}

export interface Observation {
  project: string;
  card_number: number;
  title: string;
  shape: Shape;
  challenge: Challenge;
  hand_make: Make | null;
  hand_model: string | null;
  challenger_model: string | null;
  declared_in: string;
  corrections: number | null;
  findings: number;
  inside: number;
  adjacent: number;
  outside: number;
  escapes: number;
  stops: number;
  reverted: boolean;
  hours: number | null;
  tokens: number | null;
  closed_at: string | null;
  sources: string[];
}

export interface Route {
  shape: Shape;
  challenge: Challenge;
  hand: Hand;
  challenger: Make | null;
  conclusion: Conclusion;
  why: string;
  observations: string[];
  policy?: string;
}

export interface ShapeReading {
  shape: Shape;
  observations: Observation[];
  tallies: Tally[];
  conclusion: Conclusion;
  leader: Challenge | null;
  why: string;
  confounds: string[];
}

export interface Tally {
  challenge: Challenge;
  trials: number;
  correcting: number;
  corrections: number;
  unrecorded: number;
  escapes: number;
  escaping: number;
  findings: number;
  stops: number;
  reverts: number;
  hours: number | null;
  tokens: number | null;
}

export interface TeamReading {
  project: string;
  policy: string;
  shapes: ShapeReading[];
  assigned: Composition[];
  read_at: string;
}
