// Generated by `uv run needle types` from domain/triage.py — do not edit.
import type { Actor } from "./card";

export const BAND_VALUES = ["harm outside", "lies", "loses", "costs", "looks", "nothing"] as const;
export type Band = (typeof BAND_VALUES)[number];

export const BREAKS_VALUES = ["lies", "loses", "costs", "looks", "nothing"] as const;
export type Breaks = (typeof BREAKS_VALUES)[number];

export const CORPUS_LANE_KIND_VALUES = ["split", "ruling"] as const;
export type CorpusLaneKind = (typeof CORPUS_LANE_KIND_VALUES)[number];

export const DIRECTION_VALUES = ["surface added", "surface removed", "strictness raised", "strictness lowered", "automation increased", "automation decreased", "a spend or risk bound used", "no direction"] as const;
export type Direction = (typeof DIRECTION_VALUES)[number];

export const OFTEN_VALUES = ["every-time", "sometimes", "once-seen"] as const;
export type Often = (typeof OFTEN_VALUES)[number];

export const REACH_VALUES = ["client", "money", "you", "session"] as const;
export type Reach = (typeof REACH_VALUES)[number];

export const ROUTING_VALUES = ["needs triage", "triaged now", "triaged his", "triaged when", "cannot tell", "stale"] as const;
export type Routing = (typeof ROUTING_VALUES)[number];

export const TITLE_VERDICT_VALUES = ["placeable", "unplaceable"] as const;
export type TitleVerdict = (typeof TITLE_VERDICT_VALUES)[number];

export const TRIAGE_RESULT_VALUES = ["now", "his", "when", "split", "cannot-tell"] as const;
export type TriageResult = (typeof TRIAGE_RESULT_VALUES)[number];

export interface CorpusLane {
  id: number;
  project: string;
  card_number: number;
  kind: CorpusLaneKind;
  decision: string;
  name: string;
  path: string | null;
  session_id: string | null;
  attempt: number;
  opened_at: string;
  ended_at: string | null;
  note: string | null;
  applied: boolean;
}

export interface Decision {
  decision: string;
  parent: string | null;
  project: string;
  card_number: number;
  title: string;
  at: string;
  result: TriageResult;
  words: string;
  direction: Direction | null;
  source: string;
  routing: Routing;
  fate: Fate;
}

export interface Fate {
  planned: boolean;
  started: boolean;
  folded: boolean;
  reverted: boolean;
  defect_filed_against: boolean;
  stage: string | null;
  words: string;
}

export interface Grade {
  breaks: Breaks;
  breaks_words: string;
  reach: Reach | null;
  reach_words: string | null;
  often: Often | null;
  often_words: string | null;
}

export interface Routed {
  state: Routing;
  why: string;
}

export interface Source {
  ref: string;
  path: string | null;
  text: string | null;
  fingerprint: string | null;
  note: string;
}

export interface TitleReading {
  id: number;
  project: string;
  card_number: number;
  at: string;
  verdict: TitleVerdict;
  words: string;
  failed: string[];
  title_fingerprint: string;
  session_id: string | null;
}

export interface Triage {
  id: number;
  project: string;
  card_number: number;
  at: string;
  actor: Actor;
  result: TriageResult;
  words: string;
  decision: string;
  parent: string | null;
  direction: Direction | null;
  source_ref: string | null;
  source_path: string | null;
  source_fingerprint: string | null;
  document_fingerprint: string;
  session_id: string | null;
  grade?: Grade | null;
}

export const REACH_WORDS: Record<Reach, string> = {
  "client": "a client or the public",
  "money": "money",
  "you": "you",
  "session": "a session",
};

export const OFTEN_WORDS: Record<Often, string> = {
  "every-time": "every time",
  "sometimes": "sometimes",
  "once-seen": "once seen",
};

export const BREAKS_WORDS: Record<Breaks, string> = {
  "lies": "shows something false as true",
  "loses": "loses work, data or money, or holds a card still",
  "costs": "costs a retry, a wait or a step by hand",
  "looks": "only looks wrong",
  "nothing": "describes no failure",
};

export const ROUTES_TO_THE_MACHINE: readonly Routing[] = ["triaged now"];

export const ROUTES_TO_THE_OWNER: readonly Routing[] = ["triaged his"];
