// Generated by `uv run needle types` from domain/triage.py — do not edit.
import type { Actor } from "./card";

export const CORPUS_LANE_KIND_VALUES = ["split", "ruling"] as const;
export type CorpusLaneKind = (typeof CORPUS_LANE_KIND_VALUES)[number];

export const DIRECTION_VALUES = ["surface added", "surface removed", "strictness raised", "strictness lowered", "automation increased", "automation decreased", "a spend or risk bound used", "no direction"] as const;
export type Direction = (typeof DIRECTION_VALUES)[number];

export const ROUTING_VALUES = ["needs triage", "triaged now", "triaged his", "triaged when", "cannot tell", "stale"] as const;
export type Routing = (typeof ROUTING_VALUES)[number];

export const TRIAGE_RESULT_VALUES = ["now", "his", "when", "split", "cannot-tell"] as const;
export type TriageResult = (typeof TRIAGE_RESULT_VALUES)[number];

export interface CorpusLane {
  id: number;
  project: string;
  card_number: number;
  kind: CorpusLaneKind;
  decision: string;
  name: string;
  path: string | null;
  session_id: string | null;
  attempt: number;
  opened_at: string;
  ended_at: string | null;
  note: string | null;
  applied: boolean;
}

export interface Decision {
  decision: string;
  parent: string | null;
  project: string;
  card_number: number;
  title: string;
  at: string;
  result: TriageResult;
  words: string;
  direction: Direction | null;
  source: string;
  routing: Routing;
  fate: Fate;
}

export interface Fate {
  planned: boolean;
  started: boolean;
  folded: boolean;
  reverted: boolean;
  defect_filed_against: boolean;
  stage: string | null;
  words: string;
}

export interface Routed {
  state: Routing;
  why: string;
}

export interface Source {
  ref: string;
  path: string | null;
  text: string | null;
  fingerprint: string | null;
  note: string;
}

export interface Triage {
  id: number;
  project: string;
  card_number: number;
  at: string;
  actor: Actor;
  result: TriageResult;
  words: string;
  decision: string;
  parent: string | null;
  direction: Direction | null;
  source_ref: string | null;
  source_path: string | null;
  source_fingerprint: string | null;
  document_fingerprint: string;
  session_id: string | null;
}

export const ROUTES_TO_THE_MACHINE: readonly Routing[] = ["triaged now"];

export const ROUTES_TO_THE_OWNER: readonly Routing[] = ["triaged his"];
