// Generated by `uv run needle types` from domain/verdict.py — do not edit.
import type { Place } from "./card";
import type { Column } from "./column";

export const EVIDENCE_CLASS_VALUES = ["shipped, signal read", "shipped, signal owner-only", "built under another name", "superseded", "doubted", "stale plan", "live and open"] as const;
export type EvidenceClass = (typeof EVIDENCE_CLASS_VALUES)[number];

export interface Verdict {
  evidence_class: EvidenceClass;
  evidence: string;
  to: Column | null;
}

export interface VerdictLine {
  number: number;
  title: string;
  place: Place;
  verdict: Verdict;
}

export interface VerdictsRuled {
  evidence_class: EvidenceClass;
  accepted: number;
  refused: string[];
}
