// Generated by `uv run needle types` from domain/watercooler.py — do not edit.
import type { Actor } from "./card";

export interface WatercoolerLine {
  id: number;
  project: string;
  card_number: number | null;
  actor: Actor;
  at: string;
  text: string;
}
