// Generated by `uv run needle types` from domain/window.py — do not edit.

export const WINDOW_KIND_VALUES = ["lane", "board-watch", "board-look", "board-discuss"] as const;
export type WindowKind = (typeof WINDOW_KIND_VALUES)[number];

export interface Focused {
  window: Window;
  app_id: string;
}

export interface Opened {
  window: Window;
  fresh: boolean;
  banner: string | null;
}

export interface Window {
  id: number;
  session_id: string;
  kind: WindowKind;
  app_id: string;
  address: string;
  opened_at: string;
  closed_at: string | null;
}
