"""What things are.

Every type the board reasons about lives here as a Pydantic model or a string
enum, and nothing here does anything: no I/O, no clock, no rules. `board/`
holds the rules, `infrastructure/` the storage, `api/` the doors. The frontend
mirrors this package one module per concept, generated by `needle types`.
"""
