"""Mirroring the domain into TypeScript, one module per concept.

The Pydantic models are the contract. This generator writes
`frontend/src/types/<module>.ts` from their JSON schema, and a ratchet
regenerates and compares, so a backend shape change that is not mirrored
fails the suite before it fails the page. Hand-written mirrors were the
alternative and they drift: the shape would fail at runtime, not at `tsc`.
"""

import importlib
import inspect
from enum import StrEnum
from pathlib import Path
from types import ModuleType

from pydantic import BaseModel

MODULES: list[str] = [
    "column",
    "gate",
    "document",
    "corpus",
    "row",
    "card",
    "audit",
    "project",
    "board",
]

TYPES_DIR = Path(__file__).resolve().parent.parent / "frontend" / "src" / "types"

_HEADER = "// Generated by `uv run needle types` from domain/{module}.py — do not edit.\n"


def _enums(module: ModuleType) -> list[type[StrEnum]]:
    return [
        cls
        for _, cls in inspect.getmembers(module, inspect.isclass)
        if issubclass(cls, StrEnum) and cls.__module__ == module.__name__
    ]


def _models(module: ModuleType) -> list[type[BaseModel]]:
    return [
        cls
        for _, cls in inspect.getmembers(module, inspect.isclass)
        if issubclass(cls, BaseModel) and cls.__module__ == module.__name__
    ]


def _defined_in(modules: dict[str, ModuleType]) -> dict[str, str]:
    """Type name → module name, for every enum and model in the domain."""
    home: dict[str, str] = {}
    for name, module in modules.items():
        for cls in _enums(module) + _models(module):
            home[cls.__name__] = name
    return home


def _ts_type(schema: dict[str, object], uses: set[str]) -> str:
    if "$ref" in schema:
        ref = str(schema["$ref"])
        name = ref.rsplit("/", 1)[-1]
        uses.add(name)
        return name
    if "anyOf" in schema:
        options = schema["anyOf"]
        assert isinstance(options, list)
        parts = [_ts_type(o, uses) for o in options]
        return " | ".join(parts)
    kind = schema.get("type")
    if kind == "null":
        return "null"
    if kind == "string":
        return "string"
    if kind in ("integer", "number"):
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "array":
        items = schema.get("items")
        assert isinstance(items, dict)
        inner = _ts_type(items, uses)
        return f"({inner})[]" if " | " in inner else f"{inner}[]"
    raise ValueError(f"The generator has no TypeScript for the schema {schema!r}.")


def _interface(model: type[BaseModel], uses: set[str]) -> str:
    schema = model.model_json_schema(mode="serialization")
    lines = [f"export interface {model.__name__} {{"]
    required = set(schema.get("required", []))
    properties = schema.get("properties", {})
    assert isinstance(properties, dict)
    for name, prop in properties.items():
        assert isinstance(prop, dict)
        doc = prop.get("description")
        if doc:
            lines.append(f"  /** {str(doc).strip()} */")
        optional = "" if name in required else "?"
        lines.append(f"  {name}{optional}: {_ts_type(prop, uses)};")
    lines.append("}")
    return "\n".join(lines)


def _enum_block(enum: type[StrEnum]) -> str:
    values = ", ".join(f'"{m.value}"' for m in enum)
    const = f"{_snake_upper(enum.__name__)}_VALUES"
    return (
        f"export const {const} = [{values}] as const;\n"
        f"export type {enum.__name__} = (typeof {const})[number];"
    )


def _snake_upper(name: str) -> str:
    out = ""
    for i, ch in enumerate(name):
        if ch.isupper() and i and not name[i - 1].isupper():
            out += "_"
        out += ch.upper()
    return out


def _constants(module: ModuleType, uses: set[str]) -> list[str]:
    """Module-level sets of enum members and enum→enum maps travel with the types."""
    blocks: list[str] = []
    for name, value in vars(module).items():
        if not name.isupper():
            continue
        if isinstance(value, frozenset) and value and all(isinstance(v, StrEnum) for v in value):
            member = next(iter(value))
            uses.add(type(member).__name__)
            items = ", ".join(f'"{v.value}"' for v in sorted(value, key=lambda v: v.value))
            blocks.append(f"export const {name}: readonly {type(member).__name__}[] = [{items}];")
        elif (
            isinstance(value, dict)
            and value
            and all(isinstance(k, StrEnum) and isinstance(v, StrEnum) for k, v in value.items())
        ):
            key_type = type(next(iter(value))).__name__
            val_type = type(next(iter(value.values()))).__name__
            uses.update({key_type, val_type})
            entries = ",\n".join(f'  "{k.value}": "{v.value}"' for k, v in value.items())
            blocks.append(
                f"export const {name}: Record<{key_type}, {val_type}> = {{\n{entries},\n}};"
            )
    return blocks


def generate() -> dict[str, str]:
    """Module name → file content."""
    modules = {name: importlib.import_module(f"domain.{name}") for name in MODULES}
    home = _defined_in(modules)
    out: dict[str, str] = {}
    for name, module in modules.items():
        uses: set[str] = set()
        blocks = [_enum_block(e) for e in _enums(module)]
        blocks += [_interface(m, uses) for m in _models(module)]
        blocks += _constants(module, uses)
        local = {cls.__name__ for cls in _enums(module) + _models(module)}
        imports: dict[str, set[str]] = {}
        for used in sorted(uses - local):
            if used not in home:
                raise ValueError(f"{name}.py refers to {used}, which no domain module defines.")
            imports.setdefault(home[used], set()).add(used)
        header = _HEADER.format(module=name)
        import_lines = [
            f'import type {{ {", ".join(sorted(names))} }} from "./{other}";'
            for other, names in sorted(imports.items())
        ]
        body = "\n\n".join(blocks)
        content = header
        if import_lines:
            content += "\n".join(import_lines) + "\n"
        content += "\n" + body + "\n"
        out[name] = content
    return out


def write_types(directory: Path = TYPES_DIR) -> list[Path]:
    directory.mkdir(parents=True, exist_ok=True)
    changed: list[Path] = []
    for name, content in generate().items():
        path = directory / f"{name}.ts"
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            path.write_text(content, encoding="utf-8")
            changed.append(path)
    return changed
